import React from 'react';
import { TrendingUp, Shield, Target, Users } from 'lucide-react';

export const Stats = () => {
  const stats = [
    {
      icon: Users,
      value: '10,000+',
      label: 'Active Members',
      description: 'Professional traders worldwide'
    },
    {
      icon: TrendingUp,
      value: '85%',
      label: 'Success Rate',
      description: 'Members achieving profitability'
    },
    {
      icon: Target,
      value: '$2.5M+',
      label: 'Total Profits',
      description: 'Generated by our community'
    },
    {
      icon: Shield,
      value: '99.2%',
      label: 'Capital Protection',
      description: 'Risk management success'
    }
  ];

  return (
    <section className="section-padding bg-muted/20">
      <div className="container-max mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Warriors Command
            <span className="block gradient-text">Market Respect</span>
          </h2>
          <p className="text-xl text-foreground/70 max-w-3xl mx-auto">
            Our forge produces operators whose results demand respect. No comfort zones. 
            No emotional trading. Only systematic execution and measurable outcomes.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {stats.map((stat, index) => (
            <div key={index} className="military-card text-center group">
              <div className="bg-primary/10 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 group-hover:bg-primary/20 transition-colors">
                <stat.icon className="w-8 h-8 text-primary" />
              </div>
              <div className="text-4xl font-bold mb-2 gradient-text">{stat.value}</div>
              <div className="text-lg font-semibold mb-2">{stat.label}</div>
              <p className="text-sm text-foreground/60">{stat.description}</p>
            </div>
          ))}
        </div>

        {/* Additional Context */}
        <div className="mt-16 text-center">
          <div className="military-card max-w-4xl mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-center">
              <div>
                <div className="text-2xl font-bold text-primary mb-2">4 Years</div>
                <p className="text-foreground/70">of proven methodology</p>
              </div>
              <div>
                <div className="text-2xl font-bold text-secondary mb-2">24/7</div>
                <p className="text-foreground/70">community support</p>
              </div>
              <div>
                <div className="text-2xl font-bold text-primary mb-2">90 Days</div>
                <p className="text-foreground/70">to transformation</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};